.v q0 q1 q2 q3 q4
.i q0 q1 q2 q3 q4

BEGIN
H q1
tof q0 q1
H q1
H q0
H q0
tof q4 q0
H q0
H q1
tof q4 q1
H q1
H q4
Z q0
Z q1
tof q1 q0
S* q0
tof q1 q0
S q2
tof q2 q0
T* q0
tof q2 q0
tof q2 q1
T* q1
tof q2 q1
tof q1 q0
tof q2 q0
T q0
tof q2 q0
tof q1 q0
tof q4 q0
T q0
tof q4 q0
tof q4 q1
T q1
tof q4 q1
tof q2 q0
tof q4 q0
T q0
tof q4 q0
tof q2 q0
tof q2 q1
tof q4 q1
T q1
tof q4 q1
tof q2 q1
H q4
H q1
tof q4 q1
H q1
H q0
tof q4 q0
H q0
H q0
H q1
tof q0 q1
H q1
H q2
tof q0 q2
H q2
H q4
tof q0 q4
H q4
H q0
S* q1
H q0
tof q1 q0
H q0
H q4
tof q1 q4
H q4
H q1
T* q0
T q1
tof q2 q1
T q1
tof q2 q1
H q1
H q4
tof q1 q4
H q4
H q0
tof q1 q0
H q0
S q1
H q0
H q4
tof q0 q4
H q4
H q2
tof q0 q2
H q2
H q2
tof q4 q2
H q2
H q4
H q4
tof q0 q4
H q4
H q0
T q0
tof q2 q0
T q0
tof q2 q0
T q4
tof q4 q2
T q2
tof q4 q2
H q0
H q4
tof q0 q4
H q4
H q4
H q2
tof q4 q2
H q2
H q4
tof q0 q4
H q4
H q0
S* q4
H q0
tof q4 q0
H q0
H q1
tof q4 q1
H q1
H q2
tof q4 q2
H q2
H q4
tof q1 q2
H q2
tof q1 q2
H q2
H q3
tof q1 q3
H q3
H q1
S* q1
tof q1 q0
T q0
tof q1 q0
S* q3
tof q3 q0
S* q0
tof q3 q0
tof q3 q1
S* q1
tof q3 q1
tof q1 q0
tof q3 q0
T q0
tof q3 q0
tof q1 q0
S* q4
tof q4 q1
T q1
tof q4 q1
tof q1 q0
tof q4 q0
T q0
tof q4 q0
tof q1 q0
tof q3 q0
tof q4 q0
S* q0
tof q4 q0
tof q3 q0
tof q3 q1
tof q4 q1
T q1
tof q4 q1
tof q3 q1
tof q1 q0
tof q3 q0
tof q4 q0
T q0
tof q4 q0
tof q3 q0
tof q1 q0
H q1
H q3
tof q1 q3
H q3
H q2
tof q1 q2
H q2
tof q1 q2
H q4
H q2
tof q4 q2
H q2
H q1
tof q4 q1
H q1
H q0
tof q4 q0
H q0
S q4
H q0
H q4
tof q0 q4
H q4
T q4
S* q4
H q4
T* q4
H q4
S q4
H q4
T q4
H q4
S* q4
H q4
T* q4
H q4
S q4
T* q4
H q4
T q4
H q4
S* q4
H q4
T* q4
H q4
S q4
H q4
T q4
H q4
T q4
S* q4
H q4
T* q4
H q4
S q4
H q4
T q4
H q4
S* q4
H q4
T* q4
H q4
S q4
T* q4
H q4
T q4
H q4
T* q4
S* q4
H q4
T q4
H q4
S q4
T* q4
S* q4
H q4
T q4
H q4
S q4
T* q4
S* q4
H q4
T q4
H q4
S q4
H q4
T q4
H q4
S* q4
H q4
T q4
H q4
S q4
T q4
H q4
T q4
H q4
S* q4
H q4
T q4
H q4
S q4
T q4
H q4
T* q4
H q4
H q4
tof q0 q4
H q4
H q0
T q0
tof q3 q0
T* q0
tof q3 q0
T q4
H q0
H q4
tof q0 q4
H q4
tof q0 q4
H q1
tof q0 q1
H q1
H q2
tof q0 q2
H q2
H q4
tof q0 q4
H q4
H q0
H q1
tof q4 q1
H q1
H q2
tof q4 q2
H q2
H q4
T* q0
tof q3 q0
T q0
tof q3 q0
T* q4
tof q4 q3
T q3
tof q4 q3
H q4
H q2
tof q4 q2
H q2
H q1
tof q4 q1
H q1
H q0
H q4
tof q0 q4
H q4
H q2
tof q0 q2
H q2
H q1
tof q0 q1
H q1
tof q0 q4
tof q0 q1
tof q0 q4
H q1
tof q0 q1
H q1
H q4
tof q0 q4
H q4
H q0
S* q4
H q3
tof q4 q3
H q3
H q4
T* q0
tof q3 q0
T* q0
tof q3 q0
T q4
tof q4 q3
T q3
tof q4 q3
H q4
H q3
tof q4 q3
H q3
S q4
H q0
H q4
tof q0 q4
H q4
H q1
tof q0 q1
H q1
tof q0 q4
tof q0 q1
tof q0 q1
S* q0
H q1
tof q0 q1
H q1
H q3
tof q0 q3
H q3
H q4
tof q0 q4
H q4
H q0
T* q0
H q0
H q4
tof q0 q4
H q4
H q3
tof q0 q3
H q3
H q1
tof q0 q1
H q1
S q0
tof q0 q1
S* q4
H q3
tof q4 q3
H q3
H q4
tof q0 q1
S* q0
H q1
tof q0 q1
H q1
H q4
tof q0 q4
H q4
H q0
T q0
tof q3 q0
T q0
tof q3 q0
T q4
tof q4 q3
T q3
tof q4 q3
H q0
H q4
tof q0 q4
H q4
H q1
tof q0 q1
H q1
S q0
tof q0 q1
H q4
H q3
tof q4 q3
H q3
S q4
H q0
tof q0 q1
S* q1
tof q0 q1
H q4
tof q2 q0
S* q2
tof q0 q4
tof q4 q2
S* q4
tof q0 q2
tof q0 q4
S* q4
tof q2 q4
H q2
H q2
tof q2 q4
S* q2
tof q0 q4
tof q0 q2
S* q2
tof q4 q2
tof q0 q4
S q2
tof q2 q0
H q4
tof q0 q4
H q0
H q0
tof q0 q4
S q4
H q4
S q4
H q4
H q4
S q4
H q4
S q4
H q4
S q4
H q4
H q4
S q4
H q4
S q4
H q4
S q4
H q4
H q4
S q4
H q4
S q4
H q4
H q4
S q4
H q4
H q4
H q4
H q4
H q4
S q4
H q4
H q4
S q4
H q4
S q4
H q4
S q4
H q4
S q4
H q4
S* q4
H q4
H q4
S q4
tof q0 q4
H q0
H q0
tof q0 q4
H q1
tof q1 q2
S* q2
tof q1 q2
H q4
tof q3 q1
S* q3
tof q1 q4
tof q4 q3
S* q4
tof q1 q3
tof q1 q4
S* q4
tof q3 q4
H q3
H q3
tof q3 q4
S* q3
tof q1 q4
tof q1 q3
S* q3
tof q4 q3
tof q1 q4
S q3
tof q3 q1
H q4
H q2
tof q2 q3
S* q3
tof q2 q3
END
