"""Per-step comparison of free / Hartree / PT2 / TEBD for stag_SCV and n_f -> RESULTS_TABLES.md
TEBD reference ("exact") = free_exact + [TEBD(lam=1) - TEBD(lam=0)] at the largest chi available
(truncation error largely cancels in the difference; its chi-convergence is shown)."""
import json, os, numpy as np
g = json.load(open('gauss.json')); pt = json.load(open('pt2.json'))
def tebd(c, chi, lam):
    f = f'tebd_runs/{c}_chi{chi}_lam{lam}.json'
    return json.load(open(f)) if os.path.exists(f) else None
CHIS = [64, 128, 256]
def comb(obs):
    return ([('SCV', 1)] if obs == 'stag_SCV' else [('meson', 1), ('SCV', -1)])
def gval(mode, obs, k): return sum(s * g[mode][c][k]['stag'] for c, s in comb(obs))
def a2(obs, k): return sum(s * pt[c][k][2] for c, s in comb(obs))
def tshift(obs, chi, k):
    tot = 0.0
    for c, s in comb(obs):
        t1, t0 = tebd(c, chi, 1), tebd(c, chi, 0)
        if t1 is None or t0 is None or k >= min(len(t1), len(t0)): return None
        tot += s * (t1[k]['stag'] - t0[k]['stag'])
    return tot
def ttrunc(obs, chi, k):   # raw TEBD truncation error at lam=0 (vs exact free)
    tot = 0.0
    for c, s in comb(obs):
        t0 = tebd(c, chi, 0)
        if t0 is None or k >= len(t0): return None
        tot += s * (t0[k]['stag'] - g['free'][c][k]['stag'])
    return tot
F = lambda x, p='+.6f': '—' if x is None else format(x, p)
out = ['# Per-step comparison (generated by analyze.py)\n',
       'free = exact g=0 (Gaussian); Hartree = time-dependent Hartree; PT2 = free + a2 (exact O(g^2), Wick; a1 = 0 exactly);',
       'TEBD ref = free + [TEBD(g) − TEBD(0)] at the largest χ available (χ in column). '
       '"χ-conv" = |shift(χmax) − shift(next lower χ)|; "trunc" = raw TEBD(g=0) − free at χmax (truncation error that the difference cancels).\n']
summary = {}
for obs in ('stag_SCV', 'n_f'):
    out.append(f'\n## {obs}\n')
    hdr = ('| step | free | Hartree | PT2 | TEBD ref | χmax | Hartree − TEBD | PT2 − TEBD | χ-conv | trunc (raw) |')
    out.append(hdr); out.append('|' + '---|' * (hdr.count('|') - 1))
    summary[obs] = []
    for k in range(20):
        f = gval('free', obs, k); h = gval('hartree', obs, k); p = f + a2(obs, k)
        sh = {c: tshift(obs, c, k) for c in CHIS}
        av = [c for c in CHIS if sh[c] is not None]
        cm = av[-1] if av else None
        ref = f + sh[cm] if cm else None
        conv = abs(sh[av[-1]] - sh[av[-2]]) if len(av) >= 2 else None
        tr = ttrunc(obs, cm, k) if cm else None
        out.append(f'| {k+1} | {f:.6f} | {h:.6f} | {p:.6f} | {F(ref, ".6f")} | {cm or "—"} | '
                   f'{F(None if ref is None else h - ref, "+.1e")} | {F(None if ref is None else p - ref, "+.1e")} | '
                   f'{F(conv, ".1e")} | {F(tr, "+.1e")} |')
        summary[obs].append(dict(step=k + 1, free=f, hartree=h, pt2=p, tebd_ref=ref, chi=cm, chi_conv=conv, trunc=tr))
open('RESULTS_TABLES.md', 'w').write('\n'.join(out) + '\n')
json.dump(summary, open('results_summary.json', 'w'), indent=1)
print('\n'.join(out))
