//! Exact simulation of Gidney 2025's approximate modular exponentiation
//! (`research/shor/approx-modexp.md`, `src/shor/approx.rs`): tests that fail
//! if the notebook's headline statements break.
//!
//! * every branch of the quint-level circuit returns every ancilla to 0 and
//!   ends with sign +1, for several measurement-outcome streams (all-zero,
//!   all-one, random), Shor-style and Ekerå–Håstad;
//! * the Rust precomputation equals the paper's own table code (reference
//!   tables generated by the release's `facto/algorithm/prep`, committed in
//!   `tests/data/`);
//! * the exact output distribution equals the one of an independent,
//!   genuinely quantum simulation of the paper's own Python code (committed
//!   reference, `research/data/approx-modexp/qbackend.py`) to 1e-10;
//! * one loop4 window step compiled to X/CNOT/Toffoli gates equals the
//!   quint-level step on every input, and on a superposition with random
//!   amplitudes under real projective X-basis measurements;
//! * the interference results: masking restores what unmasked approximate
//!   arithmetic destroys, and the approximation changes the output
//!   distribution by far less than the paper's bound.

#[path = "../audit_common/mod.rs"]
mod audit_common;

use audit_common::RefSv;
use num_complex::Complex64;
use qsim_lab::engines::sparse::SparseState;
use qsim_lab::gate::Gate;
use qsim_lab::shor::approx::{
    distribution, evaluate, gate_loop4_step, overlap, paper_success, plan, tv, ApproxConfig,
    ApproxParams, ConstOutcomes, Loop4Layout, Outcomes, RandomOutcomes,
};
use qsim_lab::shor::mbu::{eval_on_key, MbuOp};

fn clean(c: &ApproxConfig, o: &mut dyn Outcomes) -> Vec<u32> {
    let pl = plan(c, &mut BoxO(o));
    let (v, ft) = evaluate(c, &pl);
    assert_eq!(v.branches, 1u64 << (c.m + c.params.mask_bits));
    assert_eq!(v.bad_sign, 0, "uncorrected phase kickback: {v:?}");
    assert_eq!(v.dirty, 0, "ancilla not returned to 0: {v:?}");
    assert_eq!(v.bad_residue, 0, "wrong residue: {v:?}");
    assert_eq!(v.bad_acc, 0, "accumulator not (s + F(e)) mod T: {v:?}");
    assert_eq!(v.bad_e, 0);
    assert_eq!(v.bad_formula, 0, "F(e) differs from the table formula: {v:?}");
    ft
}

struct BoxO<'a>(&'a mut dyn Outcomes);
impl Outcomes for BoxO<'_> {
    fn draw(&mut self, len: usize) -> u64 {
        self.0.draw(len)
    }
}

fn small_shor() -> ApproxParams {
    // N = 143 = 11·13, g = 2, m = 10 exponent qubits, f = 6 kept bits (t = 2),
    // mask 2^2: every branch is 2^12
    ApproxParams::shor(143, 2, 10, [2, 2, 2, 2], 6, 2)
}

#[test]
fn every_branch_is_clean_for_every_outcome_stream() {
    for p in [
        small_shor(),
        ApproxParams::shor(899, 2, 12, [3, 2, 3, 3], 8, 3),
        ApproxParams::eh(899, 2, [2, 1, 2, 4], 8, 3),
    ] {
        let c = ApproxConfig::new(&p).unwrap();
        let f0 = clean(&c, &mut ConstOutcomes(false));
        let f1 = clean(&c, &mut ConstOutcomes(true));
        assert_eq!(f0, f1);
        for seed in 1..=6 {
            assert_eq!(clean(&c, &mut RandomOutcomes(seed)), f0);
        }
    }
}

fn loop4_key(lay: &Loop4Layout, k: u64, acc: u64) -> u128 {
    let mut key = 0u128;
    for (i, &q) in lay.k.iter().enumerate() {
        key |= u128::from((k >> i) & 1) << q;
    }
    for (i, &q) in lay.acc.iter().enumerate() {
        key |= u128::from((acc >> i) & 1) << q;
    }
    key
}

fn loop4_table(w4: usize, f: usize, trunc: u64, trial: u64) -> Vec<u64> {
    let mut rng = RandomOutcomes(trial * 7919 + 13);
    (0..1u64 << w4).map(|_| rng.draw(f) % trunc).collect()
}

/// One loop4 window step at the gate level (X/CNOT/Toffoli, X-basis
/// measurements, Z/CZ fix-ups) equals the quint-level step
/// `acc → (acc − T[k]) mod T_mod` on every input, every ancilla returns to 0 and
/// every branch ends with the same sign, for many outcome streams.
#[test]
fn gate_level_loop4_step_matches_quint_level() {
    for (w4, f, trunc) in [(2usize, 5usize, 29u64), (3, 6, 61), (2, 7, 100), (1, 4, 13)] {
        let lay = Loop4Layout::new(w4, f);
        assert!(lay.nq <= 128);
        for trial in 0..24u64 {
            let table = loop4_table(w4, f, trunc, trial);
            let mut bits = RandomOutcomes(trial * 31 + 1);
            let ops = gate_loop4_step(&lay, &table, trunc, &mut || bits.draw(1) == 1);
            let mut sign0 = None;
            for k in 0..1u64 << w4 {
                for acc in 0..trunc {
                    let (out, s) = eval_on_key(&ops, loop4_key(&lay, k, acc));
                    let want = loop4_key(&lay, k, (acc + trunc - table[k as usize]) % trunc);
                    assert_eq!(out, want, "w4={w4} f={f} k={k} acc={acc} trial={trial}");
                    assert_eq!(s, *sign0.get_or_insert(s), "sign w4={w4} k={k} acc={acc}");
                }
            }
        }
    }
}

/// The same gate-level step on a superposition with random complex
/// amplitudes, every X-basis measurement applied as a real `H` + projection
/// (probability asserted to be 1/2): the output state is the input state
/// permuted by `acc → acc − T[k] mod T_mod`, up to one global phase.
#[test]
fn gate_level_loop4_step_quantum_reference() {
    let (w4, f, trunc) = (2usize, 5usize, 29u64);
    let lay = Loop4Layout::new(w4, f);
    assert!(lay.nq <= 64);
    for trial in 0..6u64 {
        let table = loop4_table(w4, f, trunc, trial);
        let mut bits = RandomOutcomes(trial * 101 + 7);
        let ops = gate_loop4_step(&lay, &table, trunc, &mut || bits.draw(1) == 1);
        let mut rng = RandomOutcomes(trial + 99);
        let mut init = Vec::new();
        let mut norm = 0.0;
        for k in 0..1u64 << w4 {
            for acc in 0..trunc {
                let a = Complex64::new(
                    rng.draw(20) as f64 / 1e6 - 0.5,
                    rng.draw(20) as f64 / 1e6 - 0.5,
                );
                norm += a.norm_sqr();
                init.push((k, acc, a));
            }
        }
        let scale = 1.0 / norm.sqrt();
        let mut s = SparseState::from_amplitudes(
            lay.nq,
            init.iter()
                .map(|&(k, acc, a)| (loop4_key(&lay, k, acc) as u64, a * scale)),
        );
        for op in &ops {
            match *op {
                MbuOp::G(g) => s.apply_gate(&g).unwrap(),
                MbuOp::MeasX(q, m) => {
                    s.apply_gate(&Gate::H(q)).unwrap();
                    let p = s.collapse(q, m);
                    assert!((p - 0.5).abs() < 1e-9, "P(m) = {p}");
                    if m {
                        s.apply_gate(&Gate::X(q)).unwrap();
                    }
                }
                MbuOp::GlobalNeg => {}
            }
        }
        assert_eq!(s.nnz(), init.len());
        let mut phase = None;
        for &(k, acc, a) in &init {
            let out = loop4_key(&lay, k, (acc + trunc - table[k as usize]) % trunc) as u64;
            let b = s.amplitude(out);
            let ph = *phase.get_or_insert(b / (a * scale));
            assert!((b - ph * a * scale).norm() < 1e-12, "trial {trial} k={k} acc={acc}");
        }
        assert!((phase.unwrap().norm() - 1.0).abs() < 1e-12);
    }
}

/// A loop3 inner step followed by its unloop3 counterpart, both at the gate
/// level, with the wrap-qubit phase correction deferred from one to the
/// other exactly as in the paper (`push_uncompute_info((phase_wrap, vent))`):
/// identity on every input, every ancilla clean, one global sign.
#[test]
fn gate_level_loop3_pair_is_identity() {
    use qsim_lab::shor::approx::{gate_loop3_pair, Loop3Layout};
    for (w3a, w3b, p) in [(1usize, 2usize, 23u64), (2, 2, 29), (2, 3, 53), (1, 1, 11)] {
        let ell = 64 - p.leading_zeros() as usize;
        let lay = Loop3Layout::new(w3a, w3b, ell);
        assert!(lay.nq <= 128);
        for trial in 0..16u64 {
            // a table like table3a: -(v · 2^{kb w3b} · k4b) mod p
            let mut rng = RandomOutcomes(trial * 13 + p);
            let v: Vec<u64> = (0..1u64 << w3a).map(|_| 1 + rng.draw(16) % (p - 1)).collect();
            let sh = rng.draw(8) % p;
            let t3a: Vec<u64> = (0..1u64 << (w3a + w3b))
                .map(|addr| {
                    let (k4a, k4b) = (addr >> w3b, addr & ((1 << w3b) - 1));
                    (p - v[k4a as usize] * sh % p * k4b % p) % p
                })
                .collect();
            let mut bits = RandomOutcomes(trial * 977 + 5);
            let ops = gate_loop3_pair(&lay, &t3a, p, &mut || bits.draw(1) == 1);
            let mut sign0 = None;
            for l1 in 0..1u64 << w3a {
                for r in 0..1u64 << w3b {
                    for h in 0..p {
                        let mut key = 0u128;
                        for (i, &q) in lay.l1.iter().enumerate() {
                            key |= u128::from((l1 >> i) & 1) << q;
                        }
                        for (i, &q) in lay.r.iter().enumerate() {
                            key |= u128::from((r >> i) & 1) << q;
                        }
                        for (i, &q) in lay.hel.iter().enumerate() {
                            key |= u128::from((h >> i) & 1) << q;
                        }
                        let (out, s) = eval_on_key(&ops, key);
                        assert_eq!(out, key, "p={p} l1={l1} r={r} h={h} trial={trial}");
                        assert_eq!(s, *sign0.get_or_insert(s), "sign p={p} l1={l1} r={r} h={h}");
                    }
                }
            }
        }
    }
}

fn data(name: &str) -> String {
    let p = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/data/approx-modexp")
        .join(name);
    std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("{}: {e}", p.display()))
}

fn parse_list(text: &str, key: &str) -> Vec<u64> {
    let line = text
        .lines()
        .find(|l| l.starts_with(&format!("{key} = ")))
        .unwrap_or_else(|| panic!("{key} missing"));
    let body = line.split_once('[').unwrap().1.trim_end_matches(']');
    body.split(',')
        .filter(|x| !x.trim().is_empty())
        .map(|x| x.trim().parse().unwrap())
        .collect()
}

fn n8_params(periods: Vec<u64>) -> ApproxParams {
    let mut p = small_shor();
    p.forced_periods = Some(periods);
    p
}

/// The Rust precomputation equals the paper's own table code (release
/// `facto/algorithm/prep`, run by `research/data/approx-modexp/xcheck_tables.py`)
/// entry by entry.
#[test]
fn precompute_matches_paper_tables() {
    let text = data("paper_tables_n8.txt");
    let periods = parse_list(&text, "periods");
    let c = ApproxConfig::new(&n8_params(periods.clone())).unwrap();
    assert_eq!(c.periods, periods);
    assert_eq!(c.generators, parse_list(&text, "generators"));
    let t1: Vec<u64> = c
        .table1
        .iter()
        .flatten()
        .flatten()
        .map(|&x| x & 0xFFFF_FFFF)
        .collect();
    assert_eq!(t1, parse_list(&text, "table1"));
    let t3a: Vec<u64> = c.table3a.iter().flatten().flatten().flatten().copied().collect();
    let t3b: Vec<u64> = c.table3b.iter().flatten().flatten().flatten().copied().collect();
    let t3c: Vec<u64> = c.table3c.iter().flatten().copied().collect();
    let t4: Vec<u64> = c.table4.iter().flatten().flatten().copied().collect();
    assert_eq!(t3a, parse_list(&text, "table3a"));
    assert_eq!(t3b, parse_list(&text, "table3b"));
    assert_eq!(t3c, parse_list(&text, "table3c"));
    assert_eq!(t4, parse_list(&text, "table4"));
}

/// The exact output distribution equals that of an independent simulation:
/// the paper's own `approx_modexp` run on the whole superposition by a
/// genuinely quantum backend (real X-basis measurements with interference,
/// numpy FFT; `research/data/approx-modexp/qbackend.py`), to 1e-10.
#[test]
fn distribution_matches_quantum_python_backend() {
    let text = data("paper_tables_n8.txt");
    let c = ApproxConfig::new(&n8_params(parse_list(&text, "periods"))).unwrap();
    let want: Vec<f64> = data("qbackend_n8_Pj.txt")
        .lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .map(|l| l.trim().parse().unwrap())
        .collect();
    assert_eq!(want.len(), 1 << c.m);
    for seed in [3u64, 11] {
        let ft = clean(&c, &mut RandomOutcomes(seed));
        let (p, pv) = distribution(&ft, c.trunc, 1 << c.params.mask_bits, c.m, 0);
        let err = p.iter().zip(&want).map(|(a, b)| (a - b).abs()).fold(0.0, f64::max);
        assert!(err < 1e-10, "max |P_rust − P_python| = {err:e}");
        assert!((p.iter().sum::<f64>() - 1.0).abs() < 1e-12);
        assert!((pv.iter().sum::<f64>() - 1.0).abs() < 1e-12);
    }
}


/// Runs resolved gate-level ops on the repo's independent dense reference
/// state vector (`tests/audit_common`): real `H` + projection for every
/// X-basis measurement (probability asserted to be 1/2), then compares the
/// final state with `want(input key) -> output key` applied to the random
/// input amplitudes, up to one global phase.
fn refsv_check(nq: usize, ops: &[MbuOp], inputs: &[u64], want: impl Fn(u64) -> u64, seed: u64) {
    let mut rng = RandomOutcomes(seed);
    let mut sv = RefSv::new(nq);
    sv.a[0] = Complex64::new(0.0, 0.0);
    let mut amps = Vec::new();
    let mut norm = 0.0;
    for &k in inputs {
        let a = Complex64::new(rng.draw(20) as f64 / 1e6 - 0.5, rng.draw(20) as f64 / 1e6 - 0.5);
        norm += a.norm_sqr();
        amps.push((k, a));
    }
    for (k, a) in &mut amps {
        *a /= norm.sqrt();
        sv.a[*k as usize] = *a;
    }
    for op in ops {
        match *op {
            MbuOp::G(g) => sv.apply(&g),
            MbuOp::MeasX(q, m) => {
                sv.apply(&Gate::H(q));
                let p1 = sv.prob_one(q);
                let p = if m { p1 } else { 1.0 - p1 };
                assert!((p - 0.5).abs() < 1e-9, "P(m) = {p}");
                sv.collapse(q, m);
                if m {
                    sv.apply(&Gate::X(q));
                }
            }
            MbuOp::GlobalNeg => {}
        }
    }
    let mut phase = None;
    let mut moved = 0.0;
    for &(k, a) in &amps {
        let b = sv.a[want(k) as usize];
        let ph = *phase.get_or_insert(b / a);
        assert!((b - ph * a).norm() < 1e-10, "input {k}");
        moved += b.norm_sqr();
    }
    assert!((moved - 1.0).abs() < 1e-10, "probability left the expected support");
}

/// The gate-level loop4 step on the dense reference state vector (16 qubits).
#[test]
fn gate_level_loop4_step_dense_reference() {
    let (w4, f, trunc) = (2usize, 4usize, 13u64);
    let lay = Loop4Layout::new(w4, f);
    assert_eq!(lay.nq, 16);
    for trial in 0..3u64 {
        let table = loop4_table(w4, f, trunc, trial);
        let mut bits = RandomOutcomes(trial * 17 + 3);
        let ops = gate_loop4_step(&lay, &table, trunc, &mut || bits.draw(1) == 1);
        let mut inputs = Vec::new();
        let mut map = std::collections::HashMap::new();
        for k in 0..1u64 << w4 {
            for acc in 0..trunc {
                let key = loop4_key(&lay, k, acc) as u64;
                inputs.push(key);
                map.insert(key, loop4_key(&lay, k, (acc + trunc - table[k as usize]) % trunc) as u64);
            }
        }
        refsv_check(lay.nq, &ops, &inputs, |k| map[&k], trial + 5);
    }
}

/// The gate-level loop3/unloop3 step pair on the dense reference state
/// vector (18 qubits): the identity, up to a global phase.
#[test]
fn gate_level_loop3_pair_dense_reference() {
    use qsim_lab::shor::approx::{gate_loop3_pair, Loop3Layout};
    let (w3a, w3b, p) = (1usize, 1usize, 11u64);
    let lay = Loop3Layout::new(w3a, w3b, 4);
    assert_eq!(lay.nq, 18);
    for trial in 0..2u64 {
        let t3a: Vec<u64> = (0..4u64).map(|a| (p - (3 + trial) * (a >> 1 | 1) * (a & 1) % p) % p).collect();
        let mut bits = RandomOutcomes(trial * 41 + 9);
        let ops = gate_loop3_pair(&lay, &t3a, p, &mut || bits.draw(1) == 1);
        let mut inputs = Vec::new();
        for l1 in 0..2u64 {
            for r in 0..2u64 {
                for h in 0..p {
                    let key = (r << lay.r[0]) | (l1 << lay.l1[0]) | lay
                        .hel
                        .iter()
                        .enumerate()
                        .map(|(i, &q)| ((h >> i) & 1) << q)
                        .sum::<u64>();
                    inputs.push(key);
                }
            }
        }
        refsv_check(lay.nq, &ops, &inputs, |k| k, trial + 77);
    }
}

/// Consistency of the exact interference quantities: the total-variation
/// distance between the actual and the ideal (exact-arithmetic, same mask)
/// frequency distributions never exceeds the trace-distance bound
/// `sqrt(1 − |⟨ψ_ideal + c|ψ_actual⟩|²)` computed independently from the
/// deviations, for the best constant shift `c` (a shift only relabels the
/// measured output); and the distributions are normalised.
#[test]
fn tv_is_bounded_by_the_exact_fidelity() {
    use qsim_lab::shor::approx::{best_shift, shifted};
    for p in [
        ApproxParams::shor(899, 2, 14, [2, 2, 2, 2], 8, 4),
        ApproxParams::eh(899, 2, [2, 1, 2, 4], 8, 5),
        ApproxParams::shor(899, 2, 14, [2, 2, 2, 2], 8, 0),
    ] {
        let c = ApproxConfig::new(&p).unwrap();
        let ft = clean(&c, &mut RandomOutcomes(9));
        let fi: Vec<u32> = (0..1u64 << c.m).map(|e| c.ideal_trunc(e) as u32).collect();
        let w = 1u64 << p.mask_bits;
        let (ma, mb) = if p.regs.len() == 2 { (p.regs[0].0, p.regs[1].0) } else { (c.m, 0) };
        let (pa, _) = distribution(&ft, c.trunc, w, ma, mb);
        let (shift, ov) = best_shift(&ft, &fi, c.trunc, w);
        let (pi, _) = distribution(&shifted(&fi, shift, c.trunc), c.trunc, w, ma, mb);
        let (pi0, _) = distribution(&fi, c.trunc, w, ma, mb);
        // a constant shift of the output does not change the frequency distribution
        assert!(tv(&pi, &pi0) < 1e-12);
        let bound = (1.0 - ov * ov).max(0.0).sqrt();
        let d = tv(&pa, &pi);
        assert!(d <= bound + 1e-12, "TV {d} > bound {bound} ({p:?})");
        let ov2 = overlap(&ft, &shifted(&fi, shift, c.trunc), c.trunc, w);
        assert!((ov - ov2).abs() < 1e-12, "{ov} vs {ov2}");
        assert!(ov + 1e-12 >= overlap(&ft, &fi, c.trunc, w));
        assert!((pa.iter().sum::<f64>() - 1.0).abs() < 1e-12);
        let _ = paper_success(1, c.m, p.n_mod, p.generator);
    }
}

/// Regression: at toy sizes a factor of N can be an ℓ-bit prime (here
/// N = 4001·4003 with 12-bit primes). The paper's pruning step is invalid for
/// such a prime; the first port returned a prime set whose `L mod N` violated
/// the deviation constraint (3 024 811 ≥ N >> 18). The search must re-verify
/// the pruned set (as the paper's `_verify_rns_solution` does) and never use a
/// factor of N.
#[test]
fn prime_search_rejects_invalid_pruning() {
    let mut p = ApproxParams::eh_s(16_016_003, 2, 3, [4, 2, 3, 4], 18, 12);
    p.prime_bits = Some(12);
    let c = ApproxConfig::new(&p).unwrap();
    let n = 16_016_003u64;
    let dev = c.l_mod_n.min(n - c.l_mod_n);
    assert!(dev < n >> 18, "L mod N deviation {dev}");
    assert!(c.periods.iter().all(|&q| n % q != 0));
    // a forced set containing a factor of N is refused
    let mut q = p.clone();
    q.forced_periods = Some(vec![4001, 4013, 4019]);
    assert!(ApproxConfig::new(&q).is_err());
}

/// Masking is what makes approximate arithmetic usable (N = 899, Shor-style,
/// m = 14, f = 8, |P| = 9; `research/shor/approx-modexp.md` §3.4): without a
/// mask the approximate circuit's frequency distribution is far from the
/// exact-arithmetic one and loses most of its success probability; the
/// distance then halves with every mask bit (TV ∝ 1/W, not the √ of the
/// trace-distance bound) and with a 2^5 mask the success probability is
/// within 10 % of exact arithmetic with the same mask.
#[test]
fn masking_restores_interference() {
    let mut tvs = Vec::new();
    let mut succ = Vec::new();
    for mask in 0..=5usize {
        let p = ApproxParams::shor(899, 2, 14, [2, 2, 2, 2], 8, mask);
        let c = ApproxConfig::new(&p).unwrap();
        let ft = clean(&c, &mut RandomOutcomes(1));
        let fi: Vec<u32> = (0..1u64 << c.m).map(|e| c.ideal_trunc(e) as u32).collect();
        let w = 1u64 << mask;
        let (pa, _) = distribution(&ft, c.trunc, w, c.m, 0);
        let (pi, _) = distribution(&fi, c.trunc, w, c.m, 0);
        let s = |d: &[f64]| -> f64 {
            d.iter()
                .enumerate()
                .filter(|(j, _)| paper_success(*j as u64, c.m, 899, 2))
                .map(|(_, p)| p)
                .sum()
        };
        tvs.push(tv(&pa, &pi));
        succ.push((s(&pa), s(&pi)));
    }
    assert!(tvs[0] > 0.5, "no mask: TV {}", tvs[0]);
    assert!(succ[0].0 < 0.6 * succ[0].1, "no mask: success {:?}", succ[0]);
    for m in 3..=5 {
        assert!(tvs[m] < 0.6 * tvs[m - 1], "TV does not halve: {tvs:?}");
    }
    assert!(tvs[5] < 0.1, "{tvs:?}");
    assert!(succ[5].0 > 0.9 * succ[5].1, "mask 2^5: success {:?}", succ[5]);
}
