//! Exhaustive enumeration of two-block group-algebra codes over abelian
//! groups of rank <= 2, up to code equivalence.
//!
//! Every abelian group of rank <= 2 is `Z_l x Z_m` with `m | l` (invariant
//! factors), so [`groups_of_order`] lists each isomorphism class once
//! (`m = 1`: cyclic, i.e. generalised-bicycle and coprime-BB codes; `m > 1`:
//! the non-cyclic BB groups).
//!
//! The following maps send a code `(A, B)` to an equivalent code (same
//! `[[n, k, d]]`, isomorphic Tanner graphs), see `research/qec/code-discovery.md`:
//!
//! * translations `A -> A t`, `B -> B s` (independently),
//! * group automorphisms `sigma` applied to both `A` and `B`,
//! * the swap `(A, B) -> (B, A)`.
//!
//! Each orbit is visited once: `A` runs over canonical representatives of
//! `{sigma(A t)}` and every `(A, B)` with `k > 0` is reduced to a canonical
//! pair key (minimum over the whole group generated by the maps above) and
//! deduplicated.
#![allow(clippy::needless_range_loop)]

use std::collections::HashSet;

/// An abelian group `Z_l x Z_m`, elements `g = i m + j`.
#[derive(Clone, Debug)]
pub struct AbelianGroup {
    /// Order of the first cyclic factor.
    pub l: usize,
    /// Order of the second cyclic factor (`m | l`; 1 for a cyclic group).
    pub m: usize,
    /// Automorphisms as element permutations `sigma[g]`.
    pub auts: Vec<Vec<u16>>,
}

impl AbelianGroup {
    /// `Z_l x Z_m` with its full automorphism group, found by brute force over
    /// images of the two generators (each automorphism is a bijection of the
    /// `l m` elements). Elements are stored as `u16`, so `l m` must fit.
    pub fn new(l: usize, m: usize) -> Self {
        let n = l * m;
        let add = |g: usize, h: usize| ((g / m + h / m) % l) * m + (g % m + h % m) % m;
        let mul = |k: usize, g: usize| ((k * (g / m)) % l) * m + (k * (g % m)) % m;
        let order = |g: usize| (1..=n).find(|&k| mul(k, g) == 0).unwrap();
        let mut auts = Vec::new();
        for g1 in 0..n {
            if l % order(g1) != 0 {
                continue;
            }
            for g2 in 0..n {
                if m % order(g2) != 0 {
                    continue;
                }
                let mut img = vec![0u16; n];
                let mut seen = vec![false; n];
                let mut ok = true;
                for i in 0..l {
                    for j in 0..m {
                        let v = add(mul(i, g1), mul(j, g2));
                        if seen[v] {
                            ok = false;
                            break;
                        }
                        seen[v] = true;
                        img[i * m + j] = v as u16;
                    }
                    if !ok {
                        break;
                    }
                }
                if ok {
                    auts.push(img);
                }
            }
        }
        AbelianGroup { l, m, auts }
    }

    /// Group order `l m`.
    pub fn order(&self) -> usize {
        self.l * self.m
    }

    /// `g - h`.
    #[inline]
    pub fn sub(&self, g: usize, h: usize) -> usize {
        let (l, m) = (self.l, self.m);
        ((g / m + l - h / m) % l) * m + (g % m + m - h % m) % m
    }

    /// `g + h`.
    #[inline]
    pub fn add(&self, g: usize, h: usize) -> usize {
        let (l, m) = (self.l, self.m);
        ((g / m + h / m) % l) * m + (g % m + h % m) % m
    }

    /// Element `g` as `(i, j)` with `g = i m + j`.
    pub fn elem(&self, g: usize) -> (usize, usize) {
        (g / self.m, g % self.m)
    }
}

/// Isomorphism classes of abelian groups of order `n` with rank <= 2, as
/// `(l, m)` with `m | l`.
pub fn groups_of_order(n: usize) -> Vec<(usize, usize)> {
    (1..=n)
        .filter(|&m| n % m == 0 && (n / m) % m == 0)
        .map(|m| (n / m, m))
        .collect()
}

/// A subset of group elements, sorted, at most 6 elements.
pub type Sub = Vec<u16>;

fn transform(g: &AbelianGroup, s: &[u16], t: usize, sigma: &[u16]) -> Sub {
    let mut v: Sub = s.iter().map(|&x| sigma[g.sub(x as usize, t)]).collect();
    v.sort_unstable();
    v
}

/// Canonical representative of `s` under translations and automorphisms.
pub fn canon_subset(g: &AbelianGroup, s: &[u16]) -> Sub {
    let mut best: Option<Sub> = None;
    for sigma in &g.auts {
        for &t in s {
            let v = transform(g, s, t as usize, sigma);
            if best.as_ref().map_or(true, |b| v < *b) {
                best = Some(v);
            }
        }
    }
    best.unwrap()
}

/// Canonical key of the code `(A, B)` (concatenation of the two canonical
/// translates, minimised over automorphisms, translations and the swap).
pub fn canon_pair(g: &AbelianGroup, a: &[u16], b: &[u16]) -> Vec<u16> {
    let mut best: Option<Vec<u16>> = None;
    let same_w = a.len() == b.len();
    for sigma in &g.auts {
        for (p, q) in [(a, b), (b, a)] {
            if !same_w && p.len() != a.len() {
                continue;
            }
            // minimise the first block first: only translations of p
            // achieving the minimal first block can win
            let mut first: Option<Sub> = None;
            let mut cands: Vec<usize> = Vec::new();
            for &t in p {
                let v = transform(g, p, t as usize, sigma);
                match first.as_ref().map(|f| v.cmp(f)) {
                    None | Some(std::cmp::Ordering::Less) => {
                        first = Some(v);
                        cands.clear();
                        cands.push(t as usize);
                    }
                    Some(std::cmp::Ordering::Equal) => cands.push(t as usize),
                    _ => {}
                }
            }
            let first = first.unwrap();
            if let Some(b0) = &best {
                if first.as_slice() > &b0[..first.len()] {
                    continue;
                }
            }
            for &u in q {
                let w = transform(g, q, u as usize, sigma);
                let mut key = first.clone();
                key.extend_from_slice(&w);
                if best.as_ref().map_or(true, |b| key < *b) {
                    best = Some(key);
                }
            }
        }
    }
    best.unwrap()
}

/// All subsets of size `w` containing the identity `0`.
pub fn subsets_with_identity(n: usize, w: usize) -> Vec<Sub> {
    let mut out = Vec::new();
    let mut cur: Sub = vec![0];
    fn rec(n: usize, w: usize, start: usize, cur: &mut Sub, out: &mut Vec<Sub>) {
        if cur.len() == w {
            out.push(cur.clone());
            return;
        }
        for x in start..n {
            cur.push(x as u16);
            rec(n, w, x + 1, cur, out);
            cur.pop();
        }
    }
    rec(n, w, 1, &mut cur, &mut out);
    out
}

/// GF(2) rank of `[A | B]` (`|G| x 2|G|`), `|G| <= 256`.
pub fn rank_ab(g: &AbelianGroup, a: &[u16], b: &[u16]) -> usize {
    let n = g.order();
    assert!(n <= 256);
    let w = (2 * n).div_ceil(64);
    let mut rows: Vec<[u64; 8]> = vec![[0u64; 8]; n];
    for r in 0..n {
        for &x in a {
            let c = g.add(r, x as usize);
            rows[r][c / 64] ^= 1 << (c % 64);
        }
        for &x in b {
            let c = n + g.add(r, x as usize);
            rows[r][c / 64] ^= 1 << (c % 64);
        }
    }
    let mut rank = 0;
    for c in 0..2 * n {
        let (wc, bc) = (c / 64, 1u64 << (c % 64));
        let Some(p) = (rank..n).find(|&i| rows[i][wc] & bc != 0) else {
            continue;
        };
        rows.swap(p, rank);
        let pr = rows[rank];
        for i in rank + 1..n {
            if rows[i][wc] & bc != 0 {
                for t in wc..w {
                    rows[i][t] ^= pr[t];
                }
            }
        }
        rank += 1;
        if rank == n {
            break;
        }
    }
    rank
}

/// `k = 2 (|G| - rank [A|B])` (`rank H_Z = rank H_X` for abelian groups).
pub fn k_of(g: &AbelianGroup, a: &[u16], b: &[u16]) -> usize {
    2 * (g.order() - rank_ab(g, a, b))
}

/// One inequivalent code with `k > 0`.
#[derive(Clone, Debug)]
pub struct Candidate {
    /// Order of the first cyclic factor of the group.
    pub l: usize,
    /// Order of the second cyclic factor of the group.
    pub m: usize,
    /// `A` of the canonical representative (group elements, `g = i m + j`).
    pub a: Sub,
    /// `B` of the canonical representative.
    pub b: Sub,
    /// Number of logical qubits (> 0).
    pub k: usize,
}

/// Enumerates every inequivalent code of weights `(wa, wb)` (`wa <= wb`)
/// over `Z_l x Z_m` with `k > 0`, calling `f` once per equivalence class.
/// Returns `(pairs ranked, classes found)`.
pub fn enumerate_codes<F: FnMut(Candidate)>(
    g: &AbelianGroup,
    wa: usize,
    wb: usize,
    mut f: F,
) -> (u64, u64) {
    let n = g.order();
    if wa > n || wb > n {
        return (0, 0);
    }
    let sa = subsets_with_identity(n, wa);
    let sb = if wb == wa {
        sa.clone()
    } else {
        subsets_with_identity(n, wb)
    };
    let mut reps: Vec<Sub> = Vec::new();
    let mut seen: HashSet<Sub> = HashSet::new();
    for s in &sa {
        let c = canon_subset(g, s);
        if seen.insert(c.clone()) {
            reps.push(c);
        }
    }
    let mut keys: HashSet<Vec<u16>> = HashSet::new();
    let (mut ranked, mut found) = (0u64, 0u64);
    for a in &reps {
        for b in &sb {
            ranked += 1;
            let k = k_of(g, a, b);
            if k == 0 {
                continue;
            }
            let key = canon_pair(g, a, b);
            if keys.insert(key.clone()) {
                found += 1;
                f(Candidate {
                    l: g.l,
                    m: g.m,
                    a: key[..wa].to_vec(),
                    b: key[wa..].to_vec(),
                    k,
                });
            }
        }
    }
    (ranked, found)
}

impl Candidate {
    /// The candidate as a [`TwoBlockCode`](super::bicycle::TwoBlockCode) (element
    /// `g` becomes the monomial `x^(g / m) y^(g % m)`).
    pub fn code(&self) -> super::bicycle::TwoBlockCode {
        let el = |x: &u16| ((*x as usize) / self.m, (*x as usize) % self.m);
        let a: Vec<(usize, usize)> = self.a.iter().map(el).collect();
        let b: Vec<(usize, usize)> = self.b.iter().map(el).collect();
        super::bicycle::TwoBlockCode::new(self.l, self.m, &a, &b)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn automorphism_group_orders() {
        // |Aut(Z_n)| = phi(n); |Aut(Z_p x Z_p)| = |GL(2, p)|
        assert_eq!(AbelianGroup::new(12, 1).auts.len(), 4);
        assert_eq!(AbelianGroup::new(7, 1).auts.len(), 6);
        assert_eq!(AbelianGroup::new(3, 3).auts.len(), 48);
        assert_eq!(AbelianGroup::new(2, 2).auts.len(), 6);
        // |Aut(Z_4 x Z_2)| = 8
        assert_eq!(AbelianGroup::new(4, 2).auts.len(), 8);
    }

    #[test]
    fn groups_listed_once() {
        // 72 = 2^3 3^2: Z72, Z36xZ2, Z24xZ3, Z12xZ6 (Z2^3 x ... has rank 3)
        assert_eq!(
            groups_of_order(72),
            vec![(72, 1), (36, 2), (24, 3), (12, 6)]
        );
        assert_eq!(groups_of_order(36), vec![(36, 1), (18, 2), (12, 3), (6, 6)]);
    }

    #[test]
    fn rank_matches_dense() {
        let g = AbelianGroup::new(12, 6);
        let c = super::super::bicycle::TwoBlockCode::parse(12, 6, "x^3 + y + y^2", "y^3 + x + x^2");
        let idx = |(i, j): (usize, usize)| (i * 6 + j) as u16;
        let a: Vec<u16> = c.a.iter().map(|&t| idx(t)).collect();
        let b: Vec<u16> = c.b.iter().map(|&t| idx(t)).collect();
        assert_eq!(k_of(&g, &a, &b), 12);
        assert_eq!(c.k(), 12);
    }

    #[test]
    fn enumeration_finds_every_class() {
        // brute force over all pairs of 3-subsets (not only canonical A):
        // the set of canonical keys with k > 0 equals what enumerate_codes visits
        for (l, m) in [(6, 1), (9, 1), (3, 3), (6, 2), (7, 1), (12, 1)] {
            let g = AbelianGroup::new(l, m);
            let n = g.order();
            let mut all: Vec<Sub> = Vec::new();
            for a in 0..n {
                for b in a + 1..n {
                    for c in b + 1..n {
                        all.push(vec![a as u16, b as u16, c as u16]);
                    }
                }
            }
            let mut brute: HashSet<Vec<u16>> = HashSet::new();
            for a in &all {
                for b in &all {
                    if k_of(&g, a, b) > 0 {
                        brute.insert(canon_pair(&g, a, b));
                    }
                }
            }
            let mut seen: HashSet<Vec<u16>> = HashSet::new();
            enumerate_codes(&g, 3, 3, |c| {
                let mut key = c.a.clone();
                key.extend_from_slice(&c.b);
                assert!(seen.insert(key));
            });
            assert_eq!(seen, brute, "Z{l} x Z{m}");
        }
    }

    #[test]
    fn canonical_pair_is_invariant() {
        let g = AbelianGroup::new(6, 3);
        let a: Vec<u16> = vec![0, 4, 7];
        let b: Vec<u16> = vec![0, 2, 9];
        let key = canon_pair(&g, &a, &b);
        for sigma in g.auts.iter().take(5) {
            for &t in &a {
                for &u in &b {
                    let a2 = transform(&g, &a, t as usize, sigma);
                    let b2 = transform(&g, &b, u as usize, sigma);
                    assert_eq!(canon_pair(&g, &b2, &a2), key);
                    assert_eq!(k_of(&g, &a2, &b2), k_of(&g, &a, &b));
                }
            }
        }
    }
}
